### ISSUE TITLE
line 1: could not parse: ﻿0 HEAD

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#139]
Hello, I've built gedcom2html (with go1.11 windows/amd64) but when I run it with a gedcom export from latest FTM I get the following:

gedcom2html -gedcom my.ged                                                               
2018/09/24 21:43:16 line 1: could not parse: ﻿0 HEAD                                             
                                                                                                 
head my.ged                                                                              
﻿0 HEAD                                                                                          
1 CHAR UTF-8                                                                                     
1 FILE my.ged                                                            
1 SUBM @SUBM@                                                                                    
1 GEDC                                                                                           
2 VERS 5.5.1                                                                                     
2 FORM LINEAGE-LINKED                                                                            
0 @SUBM@ SUBM                                                                                    
1 NAME metaben
1 EMAIL metaben@metaben                                                                      

Is this about line endings? The version of the gedcom? Something silly I missed? Thanks :)

**Comment by elliotchance** [comment]
Your usage is correct.

Hm... I suspect it's either line endings or a BOM marker at the start of the file. Would you be able to send me the file or just the first few lines?

My email is on my profile: https://github.com/elliotchance

**Comment by elliotchance** [comment]
@metaben thanks for sending the sample, fixed: https://github.com/elliotchance/gedcom/releases/tag/v23.3.1
