### ISSUE TITLE
Windows release binaries missing exe extension

### ISSUE THREAD

**Issue by nev7n** [elliotchance/gedcom#193]
In the v31.1.1 release windows 386 zip available here: https://github.com/elliotchance/gedcom/releases/download/v31.1.1/gedcom-windows-386.zip

The executables in the bin folder are missing the .exe extension

**Comment by elliotchance** [comment]
Thanks for that. I have not tested it on Windows. Does it work if you add the extension?

**Comment by elliotchance** [comment]
I spoke too soon, I saw #194.
