### ISSUE TITLE
Living individuals names are visible in HTML output

### ISSUE THREAD

**Issue by colincameron** [elliotchance/gedcom#212]
When using gedcom2html, the generated `families.html` file shows "hidden" for living individuals, but the word "hidden" is a link to a (non-existent) html file with the individual's name.

This leaks information on living individuals. The program shouldn't attempt to create these links and should instead output the text "hidden" without any link.

**Comment by colincameron** [comment]
Even better would probably be to suppress output of the row entirely if one or both (whichever would be more appropriate) individuals are living.

**Comment by elliotchance** [comment]
This is a bug. It might have been introduced when I did the very large refactoring of the html package.

This is a good excuse to provide a more flexible option for how to deal with living individuals. Right now I’m thinking of a CLI option like:

-living [show|hidden|placeholder] where “placeholder” is the default (current behaviour).

What do you think?

**Comment by colincameron** [comment]
Just downloaded the latest version and can confirm this issue is fixed. Thanks for the quick response.
