### ISSUE TITLE
Panic on certain REPO/SOUR references

### ISSUE THREAD

**Issue by jazzboME** [elliotchance/gedcom#230]
I'm trying to parse a GEDCOM file I downloaded from ancestry.com and getting panics of the form:
``panic: line 79083: could not parse: 0 @R-1577718385@ REPO``

To be honest, I don't know if this type of reference is okay (e.g. is too long or uses an illegal character) , but I tried another validator online and it didn't have a problem with it.

If I go through and do a search and replace and remove the hyphen, so the offending line reads:
``0 @R1577718385@ REPO``
allows the line to parse.

So again, I'm not sure it is a "bug" or a malformed file, but I assume that ancestry.com files would be a fairly popular source for imported file, and it appears to create these style references for source and repository lines.

**Comment by elliotchance** [comment]
HI Kevin, it's absolutely a bug. The regexp that parses the line needs to be more flexible:

https://github.com/elliotchance/gedcom/blob/master/decoder.go#L152

I welcome a PR, or I will fix this tonight.
