### ISSUE TITLE
make

### ISSUE THREAD

**Issue by DomeDan** [elliotchance/gedcom#251]
Hello!

I'm not able to build the gedcom tools,
after installing go-1.7 and setting goroot and gopath and some go packages
I ended up where make was looking for a directory in elliotchange that I didnt have
 
> make
> go test -race ./...
> github.com/elliotchance/gedcom
> name_type_test.go:4:2: cannot find package "github.com/elliotchance/tf" in any of:
>         /usr/lib/go-1.7/src/github.com/elliotchance/tf (from $GOROOT)
>         /home/domedan/gopath/src/github.com/elliotchance/tf (from $GOPATH)
> FAIL    github.com/elliotchance/gedcom [setup failed]

**Comment by elliotchance** [comment]
The package manager I'm using is called `dep` (https://github.com/golang/dep). It works just like any other package manager you're used to. Simply run this in the project root:

```bash
dep ensure
```

It will install the dependencies into a folder called `vendor` in the project root.

**Comment by DomeDan** [comment]
Aha, I see!
Got no experience with the go language but the dep debian packages installed without pain.
But still was not able to build:

> make
> go test -race ./...
> # gedcom/vendor/github.com/elliotchance/gedcom
> vendor/github.com/elliotchance/gedcom/document.go:55: undefined: sync.Map
> # gedcom
> ./document.go:55: undefined: sync.Map
> FAIL    gedcom [build failed]
> Makefile:3: receptet för målet ”test” misslyckades
> make: *** [test] Fel 2

**Comment by elliotchance** [comment]
The version of Go you have installed is quite old. sync.Map was introduced in go1.9. Officially they only support the last 3 minor releases and the latest version is go1.12.

**Comment by elliotchance** [comment]
@DomeDan did you manage to fix the issue?

**Comment by elliotchance** [comment]
I am closing this issue because it has gone stale. Also, this project no longer uses `dep`.
