### ISSUE TITLE
gedcom2html: individuals pages - additional names rows are missing

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#275]
Hi Elliot - when looking at the page of an individual who has eg. 2 Names, the Additional Names table has a counter of 1, but has no visible rows. Attached is a screenshot from FTM prior to export, and of what I can see from gedcom2html.

![nma](https://user-images.githubusercontent.com/8319271/58431053-047fff80-80a4-11e9-879c-c9df93d71e5f.png)
![ftm-nma](https://user-images.githubusercontent.com/8319271/58431054-047fff80-80a4-11e9-8baa-af050788db3c.png)

**Comment by elliotchance** [comment]
That clearly looks like a bug. Do you know how to copy the GEDCOM lines for part or all of Nina Mary Andrews?

**Comment by metaben** [comment]
Here you go. This is a single person export from FTM2017. The names are on Lines 22 and 88.

HTH.
[gedcomtest-ninamaryandrews.zip](https://github.com/elliotchance/gedcom/files/4114601/gedcomtest-ninamaryandrews.zip)
