### ISSUE TITLE
gedcom2html: Spouses and Children are not listed

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#276]
Hi Elliot. Not sure if feature not implemented, or a bug. This individual had two husbands and six children. If I go to the Individual page of one of the children, the parents are correctly listed, so the family is in the data!

![Annotation 2019-05-27 172435](https://user-images.githubusercontent.com/8319271/58431184-8cfea000-80a4-11e9-81de-e2bbd98f74ef.png)

**Comment by elliotchance** [comment]
I see no reason why the data would not show. Is this happening for this individual only or are you seeing it with other individuals?

The easiest way to investigate is if you can send me the snippet of GEDCOM for the individual that was used to generate this page.

**Comment by metaben** [comment]
Can you work with this? It's just a small branch of a tree, no living people, exported from FTM2017.

In every export I have tried, you can go upwards from children to parents, but never downwards from parents as no spouses nor children are shown.

Related: the Individuals pages do not seem to have generated correctly. Some are blank, some are missing.

HTH.

[gedcomtest-evaellenpreece.zip](https://github.com/elliotchance/gedcom/files/4114474/gedcomtest-evaellenpreece.zip)

**Comment by elliotchance** [comment]
Hi @metaben - I have fixed both issues. Try at least v39.0.1: https://github.com/elliotchance/gedcom/releases

Mary Preece will not show up in the output unless living people are shown because she has no baptism date.

**Comment by metaben** [comment]
I'll give it a go. Can I just mention that it's kinda hard to see version right now (except the Releases page itself of course).

c:\tools>gedcom.exe
2020/01/27 21:57:39 ERROR: Missing command, use one of:
        c:\tools\gedcom.exe diff      - Compare gedcom files
        c:\tools\gedcom.exe publish   - Publish as HTML
        c:\tools\gedcom.exe query     - Query with gedcomq
        c:\tools\gedcom.exe tune      - Used to calculate ideal weights and similarities
c:\tools>gedcom.exe -v
2020/01/27 21:57:43 ERROR: unknown command: -v
c:\tools>gedcom.exe /?
2020/01/27 21:57:45 ERROR: unknown command: /?
c:\tools>gedcom.exe --version
2020/01/27 21:57:48 ERROR: unknown command: --version
c:\tools>gedcom.exe --help
2020/01/27 21:57:52 ERROR: unknown command: --help
c:\tools>gedcom.exe -h
2020/01/27 21:57:54 ERROR: unknown command: -h
c:\tools>

**Comment by metaben** [comment]
> Mary Preece will not show up in the output unless living people are shown because she has no baptism date.

That's ok, I was running _gedcom publish_ with _-living show._

**Comment by elliotchance** [comment]
> I'll give it a go. Can I just mention that it's kinda hard to see version right now (except the Releases page itself of course).

Yes, you're right. I'll do this soon: https://github.com/elliotchance/gedcom/issues/296
