### ISSUE TITLE
gedcom2html: link from Place back to Individual is "Unknown"

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#277]
Hi Elliot. Here's an example of where the Individual links to the Place via a Marriage, but the Place doesn't go back to the Individual. The name is given as Unknown. See below :]

![Annotation 2019-05-27 173132](https://user-images.githubusercontent.com/8319271/58431419-9a685a00-80a5-11e9-852b-f49e04d3d332.png)
![Annotation 2019-05-27 173202](https://user-images.githubusercontent.com/8319271/58431420-9b00f080-80a5-11e9-8d06-28b892896dea.png)

**Comment by elliotchance** [comment]
Hmm, that is unusual. My first thought is that the pointer (which points to the ID of the spouse) in the marriage event is different from the pointer of the actual individual.

I would need to see the GEDCOM for the marriage event and individual to really diagnose it. Can you supply those?

**Comment by elliotchance** [comment]
I am closing this because it has gone stale. It's possible the issue has been resolved indirectly and I would need the original GEDCOM to confirm and investigate this bug. Please reopen if the GEDCOM file can be provided.
