### ISSUE TITLE
gedcom2text - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by sarnobat** [elliotchance/gedcom#279]
### Input
```./gedcom2text -gedcom path/to/my.ged```

### Output
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.main.func1(0x6b, 0x6a, 0xc00009fb00)
	/home/travis/gopath/src/github.com/elliotchance/gedcom/gedcom2text/main.go:71 +0xfd
sort.insertionSort_func(0xc000091ea0, 0xc0003e3200, 0x64, 0x78)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/sort/zfuncversion.go:12 +0x93
sort.stable_func(0xc000091ea0, 0xc0003e3200, 0xf5)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/sort/zfuncversion.go:167 +0x51
sort.SliceStable(0x1164440, 0xc0003e31e0, 0xc00009fea0)
	/home/travis/.gimme/versions/go1.11.5.linux.amd64/src/sort/slice.go:31 +0x106
main.main()
	/home/travis/gopath/src/github.com/elliotchance/gedcom/gedcom2text/main.go:70 +0x51f
```

## Comments

* I've tried this with 35.something and 30.0.0
* Why does it say `/home/travis`?
* I've tried it with 2 separate gedcom files (though they might have some overlap - I'm not sure)
* Other tools seem to work fine, e.g. `./gedcom2json -gedcom path/to/my.ged`

**Comment by elliotchance** [comment]
Can you please confirm you get the error with the latest version: v37.0.3?

Are you trying to extract a specific type of information from the GEDCOM?

It includes `/home/travis` in the stack trace because the binary is created with Travis CI.

**Comment by sarnobat** [comment]
Thank you for the quick reply. Here I tried with the latest version `v37.0.3` actually (not 35.x), same problem.

- I tried the latest version on Mac OS X and on Linux
- I also tried v32.something (sorry for the imprecise details, I don't remember exactly).
- `gedcom2json` works fine
- Attached is my gedcom file (please remove the `.txt` file):

[my_family.ged.txt](https://github.com/elliotchance/gedcom/files/3643374/my_family.ged.txt)

I really hope I can use your software, it looks like it's the best CLI tool out there.

**Comment by elliotchance** [comment]
Thank you for providing the GEDCOM, that's what I was going to ask for next. I'll investigate.

**Comment by sarnobat** [comment]
Has this repo changed significantly since I filed this ticket? I don't see gedcom2text anymore.

**Comment by elliotchance** [comment]
@sarnobat - gedcom2text has been removed because it is not worth maintaining. Instead, you can use `gedcom query` with CSV output for much more control about how you want text to be output. It also supports other formats and complex filtering.

This query returns the name, birth and death in a 3 column CSV:

```bash
gedcom query -format csv -gedcom file.ged '.Individuals | { name: .Name, born: .Birth, death: .Death }'
```

```txt
1881,1958,Edgar Percival Chance
31 Mar 1883,26 Aug 1953,Clinton Frederick Chance
1877,,Susan Chance
1886,,Agnes Elizabeth Heming
```

**Comment by elliotchance** [comment]
@sarnobat does this solution work for you?

**Comment by sarnobat** [comment]
Thanks for asking and apologies for not responding, I didn't realize the ticket was left open.

My initial use case doesn't lend itself to row-based data so for now I'm creating my own solution (a fuse file system works well!).

I'd love to learn Golang one day so if I do I'd use your project as a vehicle. Thanks for these amazing tools.
