### ISSUE TITLE
Using gedcomq: 2019/12/23 12:39:36 expected expression

### ISSUE THREAD

**Issue by brewer-michael** [elliotchance/gedcom#283]
I downloaded v37.0.3 for Windows, and am trying to run gedcomq. I keep getting the error "2019/12/23 12:39:36 expected expression" without any context. When I enter only a gedcom filepath, I get the following:
  -format string
        Output format, can be one of the following: "json", "pretty-json", "gedcom" or
        "csv". (default "json")
  -gedcom value
        Path to the GEDCOM file. You may specify more than one document by providing
        -gedcom with an argument multiple times. You must provide at least one document.

A few examples of this command on the main README.md would be great

**Comment by elliotchance** [comment]
Can you please provide the complete command that is failing?

**Comment by elliotchance** [comment]
@brewer-michael I am closing this because it's gone stale. Please reopen this issue if you revisit this.
