### ISSUE TITLE
Publish: Add option to exclude duplicate names

### ISSUE THREAD

**Issue by metaben** [elliotchance/gedcom#297]
Have you got any thoughts on de-duplicating these? Not sure how much logic you want to build in.

![image](https://user-images.githubusercontent.com/8319271/73219719-af295000-4154-11ea-9613-ddda68c02b3b.png)

I wasn't expecting to see this, bit of a surprise, but I looked at the raw gedcom and I see the values are there. Maybe FTM hides them. If FTM does, here's the workflow its skewed me to:

Name (already known and sourced): John Johnson
Name (in new source material but totally wrong): Jon Gonson

FTM would let you "discard" the name of Jon Gonson, but allow you to link the source up to the good name of John Johnson. So you're improving quality of research, but without polluting/diluting with digitisation mistakes (which might lead to manual corrections). Does this make sense? Is this evidenced in the gedcom?

**Comment by elliotchance** [comment]
Yep. That's super easy. I'll add a `-hide-duplicate-names` or similar flag to `gedcom publish`.
