### ISSUE TITLE
Unable to build gedcom 39.2.0 from source

### ISSUE THREAD

**Issue by degb00** [elliotchance/gedcom#302]
I recently downloaded the gedcom 39.2.0 source code. I am using Ubuntu 18.04 as my OS.

I installed make and go this way:

sudo apt install make
sudo apt install make-guile
sudo snap install go
sudo apt  install gccgo-go

$ go version
go version go1.10.3 gccgo (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0 linux/amd64

When I run make, it fails. I captured the output in the attached file.
[make.out.txt](https://github.com/elliotchance/gedcom/files/4471825/make.out.txt)

**Comment by degb00** [comment]
I suspect go 1.10 is too old.

I removed go version 1.10 this way:
sudo snap remove go
sudo apt install gccgo-go

I installed go 1.14 using the directions from here: https://golang.org/doc/install?download=go1.14.2.linux-amd64.tar.gz

I unpacked the tarball into /usr/local as they suggested. I added the go directory to my path:
export PATH=$PATH:/usr/local/go/bin

When I run make, I get this output, and no executable called gedcom.

go test -race ./...
go: downloading github.com/elliotchance/tf v1.5.0
go: downloading github.com/cheggaaa/pb v1.0.27
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/google/go-cmp v0.2.0
go: downloading golang.org/x/text v0.3.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading golang.org/x/sys v0.0.0-20190114130336-2be517255631
ok  	github.com/elliotchance/gedcom	0.988s
?   	github.com/elliotchance/gedcom/cmd/gedcom	[no test files]
ok  	github.com/elliotchance/gedcom/html	0.071s
ok  	github.com/elliotchance/gedcom/html/core	0.045s
ok  	github.com/elliotchance/gedcom/q	0.163s
?   	github.com/elliotchance/gedcom/util	[no test files]

**Comment by degb00** [comment]
Here is the final step to build the executable:

go build ./cmd/gedcom

**Comment by elliotchance** [comment]
Hi @degb00 - I'm going to close this since it wasn't actually a problem with this repo, but rather just a version of go that was too old to build it.
