### ISSUE TITLE
ERROR: no such variable d

### ISSUE THREAD

**Issue by dschmidtadv** [elliotchance/gedcom#314]
I am getting above mentioned error when attempting to merge two files:
ged d -gedcom /Users/dschmidt/Downloads/geneanet.ged  -format gedcom   'IndividualBySurroundingSimilarityMergeFunction(Document1, Document2)' > merged.ged

**Comment by elliotchance** [comment]
There is only one gedcom file provided, the command needs to look more like:

```
gedcom query -gedcom file1.ged -gedcom file2.ged -format gedcom \
  'MergeDocumentsAndIndividuals(Document1, Document2)' > merged.ged
```

Ref: https://godoc.org/github.com/elliotchance/gedcom/q

**Comment by dschmidtadv** [comment]
@elliotchance  Sorry, my bad, it was actually
```
 /Users/dschmidt/Downloads/bin/gedcom query  -gedcom /Users/dschmidt/Downloads/combined0820/combined0820.ged d -gedcom /Users/dschmidt/Downloads/geneanet.ged  -format gedcom   'MergeDocumentsAndIndividuals(Document1, Document2)' > merged.ged 
```
