### ISSUE TITLE
Age()

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/gedcom#9]
`func Age(individual IndividualNode, event Node) time.Duration`

Tries to calculate the age the individual was at the time of the even using the birth date. If the birth date it not available or there is no date in the event then 0 is returned.

**Comment by murnux** [comment]
Hello, I would like to take a look at this. I had some questions.

- I'm new to the software, and GEDCOM in general, how should I test to make sure the Age() func runs properly? 

- Should this be placed in individual_node.go? 

Thanks.

**Comment by elliotchance** [comment]
Hi @murnux, yes you are right that it would be part of `individual_node.go` and actually the definition would be (more accurately):

```go
func (node *IndividualNode) Age(event Node) time.Duration
```

I don't want to give away the answer too easily, but have a look at `Years()` and `EstimatedBirthDate()`... 😄
